version: '3'
services:
  lavalink:
    image: lofi-cat:dev
    build:
      context: .
    ports:
      - '2333:2333'
    command: java -jar Lavalink.jar
  lofi_cat:
    image: lofi-cat:dev
    build:
      context: .
    links:
      - lavalink
    command: node index.js